import { Milestone } from './vaultTypes';

export const INITIAL_MILESTONES: Milestone[] = [
  // --- ORB JOURNEY ---
  {
    id: 'orb_awakening',
    name: 'Orb Awakening',
    description: 'Begin your very first focus session on Timerra to wake the central solar core.',
    category: 'orb',
    rarity: 'Common',
    xpAward: 100,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'orb_resonance',
    name: 'Orb Resonance',
    description: 'Complete 10 focused study cycles to sync with the solar core.',
    category: 'orb',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'orb_harmony',
    name: 'Orb Harmony',
    description: 'Log 25 fully completed focus sessions in history.',
    category: 'orb',
    rarity: 'Rare',
    xpAward: 350,
    progressCurrent: 0,
    progressTarget: 25,
  },
  {
    id: 'orb_ascension',
    name: 'Orb Ascension',
    description: 'Evolve your orb core by completing 50 total focus sessions.',
    category: 'orb',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 50,
  },
  {
    id: 'orb_fusion',
    name: 'Orb Fusion',
    description: 'Establish a state of deep flow with 100 logged focus cycles.',
    category: 'orb',
    rarity: 'Epic',
    xpAward: 750,
    progressCurrent: 0,
    progressTarget: 100,
  },
  {
    id: 'orb_nova',
    name: 'Orb Nova',
    description: 'Ignite the stellar furnace by accumulating 100 hours of focused work.',
    category: 'orb',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 100,
  },
  {
    id: 'orb_eclipse',
    name: 'Orb Eclipse',
    description: 'Pass into the shadow of giants with 250 total focus hours.',
    category: 'orb',
    rarity: 'Legendary',
    xpAward: 1500,
    progressCurrent: 0,
    progressTarget: 250,
  },
  {
    id: 'orb_infinity',
    name: 'Orb Infinity',
    description: 'Achieve boundless temporal sync by accumulating 500 lifetime focus hours.',
    category: 'orb',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 500,
  },
  {
    id: 'orb_singularity',
    name: 'Orb Singularity',
    description: 'Collapse the spacetime of work by achieving 1,000 lifetime focus hours.',
    category: 'orb',
    rarity: 'Celestial',
    xpAward: 5000,
    progressCurrent: 0,
    progressTarget: 1000,
  },

  // --- CAPSULE MASTERY ---
  {
    id: 'capsule_first',
    name: 'First Capsule',
    description: 'Create your first local Timerra Capsule backup file to lock in your work records.',
    category: 'capsule',
    rarity: 'Common',
    xpAward: 150,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'capsule_export',
    name: 'Secure Export',
    description: 'Export and safely download a local client-side backup payload.',
    category: 'capsule',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'capsule_restore',
    name: 'Perfect Restore',
    description: 'Restore a local encrypted capsule with zero data loss.',
    category: 'capsule',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'capsule_integrity',
    name: '100% Integrity',
    description: 'Validate capsule signature checksum to confirm perfect decentralized persistence.',
    category: 'capsule',
    rarity: 'Epic',
    xpAward: 400,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'capsule_cross_device',
    name: 'Cross Device Success',
    description: 'Import focus records from another client session using capsule exchange.',
    category: 'capsule',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'capsule_archivist',
    name: 'Capsule Archivist',
    description: 'Build a permanent library by storing 5 local capsule backups.',
    category: 'capsule',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 5,
  },
  {
    id: 'capsule_guardian',
    name: 'Capsule Guardian',
    description: 'Secure your data actively for 30 consecutive days of file storage.',
    category: 'capsule',
    rarity: 'Legendary',
    xpAward: 1200,
    progressCurrent: 0,
    progressTarget: 30,
  },
  {
    id: 'capsule_architect',
    name: 'Capsule Architect',
    description: 'Maintain 10 active encrypted restore nodes in your library.',
    category: 'capsule',
    rarity: 'Mythic',
    xpAward: 2000,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'capsule_master',
    name: 'Capsule Master',
    description: 'Integrate 25 distinct capsule archives across your local storage.',
    category: 'capsule',
    rarity: 'Celestial',
    xpAward: 4000,
    progressCurrent: 0,
    progressTarget: 25,
  },

  // --- MOOD EXPLORER ---
  {
    id: 'mood_first',
    name: 'First Atmosphere',
    description: 'Tune into an environmental soundscape for at least 15 minutes of focus.',
    category: 'mood',
    rarity: 'Common',
    xpAward: 100,
    progressCurrent: 0,
    progressTarget: 15,
  },
  {
    id: 'mood_rain',
    name: 'Rain Lover',
    description: 'Focus under the gentle patter of Rain for at least 2 hours.',
    category: 'mood',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 120,
  },
  {
    id: 'mood_galaxy',
    name: 'Galaxy Dreamer',
    description: 'Stare into deep cosmos with Cosmic atmosphere active for 2 hours.',
    category: 'mood',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 120,
  },
  {
    id: 'mood_ocean',
    name: 'Ocean Walker',
    description: 'Sync your breathing with Ocean tides for at least 2 hours.',
    category: 'mood',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 120,
  },
  {
    id: 'mood_forest',
    name: 'Forest Soul',
    description: 'Immerse your senses in green Forest whispers for 2 hours.',
    category: 'mood',
    rarity: 'Epic',
    xpAward: 400,
    progressCurrent: 0,
    progressTarget: 120,
  },
  {
    id: 'mood_aurora',
    name: 'Aurora Hunter',
    description: 'Witness the dance of atmospheric Aurora light for 2 hours.',
    category: 'mood',
    rarity: 'Epic',
    xpAward: 400,
    progressCurrent: 0,
    progressTarget: 120,
  },
  {
    id: 'mood_cyber',
    name: 'Cyber Night',
    description: 'Code or work in the neon glow of Cyber Lounge soundscapes for 5 hours.',
    category: 'mood',
    rarity: 'Legendary',
    xpAward: 800,
    progressCurrent: 0,
    progressTarget: 300,
  },
  {
    id: 'mood_zen',
    name: 'Zen Spirit',
    description: 'Achieve mental stillness with Zen garden tunes for 5 hours.',
    category: 'mood',
    rarity: 'Legendary',
    xpAward: 800,
    progressCurrent: 0,
    progressTarget: 300,
  },
  {
    id: 'mood_campfire',
    name: 'Fire Realm',
    description: 'Kindle your passion with crackling Campfire crackles for 5 hours.',
    category: 'mood',
    rarity: 'Mythic',
    xpAward: 1500,
    progressCurrent: 0,
    progressTarget: 300,
  },
  {
    id: 'mood_moonlight',
    name: 'Moonlight Focus',
    description: 'Bask in midnight serenity for 10 hours of study.',
    category: 'mood',
    rarity: 'Mythic',
    xpAward: 1500,
    progressCurrent: 0,
    progressTarget: 600,
  },
  {
    id: 'mood_master',
    name: 'Master Explorer',
    description: 'Use and master every single Timerra Mood atmosphere.',
    category: 'mood',
    rarity: 'Celestial',
    xpAward: 3500,
    progressCurrent: 0,
    progressTarget: 9,
  },

  // --- FOCUS LEGACY ---
  {
    id: 'legacy_step',
    name: 'First Step',
    description: 'Log 5 minutes of study session.',
    category: 'legacy',
    rarity: 'Common',
    xpAward: 100,
    progressCurrent: 0,
    progressTarget: 5,
  },
  {
    id: 'legacy_momentum',
    name: 'Momentum',
    description: 'Complete 4 study sessions in a single 24-hour cycle.',
    category: 'legacy',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 4,
  },
  {
    id: 'legacy_flow',
    name: 'Flow State',
    description: 'Run a study session without pausing or looking away for 25 minutes.',
    category: 'legacy',
    rarity: 'Rare',
    xpAward: 300,
    progressCurrent: 0,
    progressTarget: 25,
  },
  {
    id: 'legacy_current',
    name: 'Deep Current',
    description: 'Spend 3 full hours studying in Deep Focus mode.',
    category: 'legacy',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 180,
  },
  {
    id: 'legacy_silent',
    name: 'Silent Master',
    description: 'Study with mechanical Tick sound enabled for an entire session.',
    category: 'legacy',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'legacy_endurance',
    name: 'Endurance',
    description: 'Complete a single 60-minute Marathon focus session.',
    category: 'legacy',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 60,
  },
  {
    id: 'legacy_limit_break',
    name: 'Limit Break',
    description: 'Spend 4 continuous hours of focus inside the Timerra core.',
    category: 'legacy',
    rarity: 'Legendary',
    xpAward: 1200,
    progressCurrent: 0,
    progressTarget: 240,
  },
  {
    id: 'legacy_focus',
    name: 'Focus Legacy',
    description: 'Accumulate a total of 100 completed focus sessions in history.',
    category: 'legacy',
    rarity: 'Mythic',
    xpAward: 2000,
    progressCurrent: 0,
    progressTarget: 100,
  },
  {
    id: 'legacy_living_legend',
    name: 'Living Legend',
    description: 'Sustain your reputation with 500 completed sessions.',
    category: 'legacy',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 500,
  },
  {
    id: 'legacy_beyond_time',
    name: 'Beyond Time',
    description: 'Outlive the clock with 1,000 completed focus sessions.',
    category: 'legacy',
    rarity: 'Celestial',
    xpAward: 5000,
    progressCurrent: 0,
    progressTarget: 1000,
  },

  // --- ENERGY FLOW ---
  {
    id: 'energy_morning',
    name: 'Perfect Morning',
    description: 'Settle in and complete a session early between 5:00 AM and 9:00 AM.',
    category: 'energy',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'energy_evening',
    name: 'Golden Evening',
    description: 'Maintain deep concentration by finishing a study session between 5:00 PM and 9:00 PM.',
    category: 'energy',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'energy_night',
    name: 'Night Resonance',
    description: 'Sync with late hours by logging focus between 10:00 PM and 2:00 AM.',
    category: 'energy',
    rarity: 'Rare',
    xpAward: 300,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'energy_weekend',
    name: 'Weekend Warrior',
    description: 'Finish 5 focus sessions over Saturday and Sunday.',
    category: 'energy',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 5,
  },
  {
    id: 'energy_recovery',
    name: 'Recovery Expert',
    description: 'Complete 10 Short Break intervals to restore cognitive batteries.',
    category: 'energy',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'energy_rhythm',
    name: 'Balanced Rhythm',
    description: 'Complete exactly 4 study sessions and 4 break periods in one day.',
    category: 'energy',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 1,
  },

  // --- MIND EVOLUTION ---
  {
    id: 'mind_zero_distraction',
    name: 'Zero Distractions',
    description: 'Power through a full 25+ min session without a single pause trigger.',
    category: 'mind',
    rarity: 'Rare',
    xpAward: 300,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'mind_perfect_week',
    name: 'Perfect Week',
    description: 'Log focused sessions for 7 consecutive calendar days.',
    category: 'mind',
    rarity: 'Epic',
    xpAward: 600,
    progressCurrent: 0,
    progressTarget: 7,
  },
  {
    id: 'mind_consistent',
    name: 'Consistent Mind',
    description: 'Engage with Timerra on 15 different days of study.',
    category: 'mind',
    rarity: 'Epic',
    xpAward: 600,
    progressCurrent: 0,
    progressTarget: 15,
  },
  {
    id: 'mind_fortress',
    name: 'Mental Fortress',
    description: 'Build a fortress by locking in 10 focus sessions in one single week.',
    category: 'mind',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'mind_calm_focus',
    name: 'Calm Focus',
    description: 'Build quiet focus by logging 15 total study hours in a week.',
    category: 'mind',
    rarity: 'Legendary',
    xpAward: 1200,
    progressCurrent: 0,
    progressTarget: 15,
  },
  {
    id: 'mind_discipline',
    name: 'Master Discipline',
    description: 'Maintain a pristine 30-day focus streak to solidify the habit loop.',
    category: 'mind',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 30,
  },

  // --- BALANCE PATH ---
  {
    id: 'balance_healthy',
    name: 'Healthy Break',
    description: 'Successfully complete 1 Short Break cycle after studying.',
    category: 'balance',
    rarity: 'Common',
    xpAward: 100,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'balance_no_burnout',
    name: 'No Burnout',
    description: 'Take a long restorative break immediately after completing 4 consecutive focus cycles.',
    category: 'balance',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'balance_perfect_ratio',
    name: 'Perfect Balance',
    description: 'Track at least 30 minutes of rest time for every 2 hours of focus logged.',
    category: 'balance',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'balance_recovery_complete',
    name: 'Recovery Complete',
    description: 'Relax for a total of 15 break minutes.',
    category: 'balance',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 15,
  },
  {
    id: 'balance_well_rested',
    name: 'Well Rested',
    description: 'Execute 3 restorative Long Breaks in a single calendar week.',
    category: 'balance',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 3,
  },
  {
    id: 'balance_refresh',
    name: 'Mind Refresh',
    description: 'Dedicate 5 total hours to break/mindful rest modes.',
    category: 'balance',
    rarity: 'Mythic',
    xpAward: 2000,
    progressCurrent: 0,
    progressTarget: 300,
  },

  // --- SUMMIT JOURNEY ---
  {
    id: 'summit_base_camp',
    name: 'Base Camp',
    description: 'Establish a study routine by setting a custom daily focus goal.',
    category: 'summit',
    rarity: 'Common',
    xpAward: 100,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'summit_camp_one',
    name: 'Camp One',
    description: 'Climb the first ridge by logging 5 hours of total focus.',
    category: 'summit',
    rarity: 'Rare',
    xpAward: 250,
    progressCurrent: 0,
    progressTarget: 5,
  },
  {
    id: 'summit_camp_two',
    name: 'Camp Two',
    description: 'Reach high ground by accumulating 15 total focus hours.',
    category: 'summit',
    rarity: 'Rare',
    xpAward: 300,
    progressCurrent: 0,
    progressTarget: 15,
  },
  {
    id: 'summit_camp_three',
    name: 'Camp Three',
    description: 'Climb to mountain altitude with 30 total focus hours.',
    category: 'summit',
    rarity: 'Epic',
    xpAward: 500,
    progressCurrent: 0,
    progressTarget: 30,
  },
  {
    id: 'summit_push',
    name: 'Summit Push',
    description: 'Commit to high effort by focusing for 3 hours in a single day.',
    category: 'summit',
    rarity: 'Epic',
    xpAward: 600,
    progressCurrent: 0,
    progressTarget: 180,
  },
  {
    id: 'summit_reached',
    name: 'Reached Summit',
    description: 'Scale the peak of productivity with 50 focus hours completed.',
    category: 'summit',
    rarity: 'Legendary',
    xpAward: 1200,
    progressCurrent: 0,
    progressTarget: 50,
  },
  {
    id: 'summit_above_clouds',
    name: 'Above The Clouds',
    description: 'Ascend to the highest echelon by recording 150 hours of total study.',
    category: 'summit',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 150,
  },

  // --- HIDDEN RELICS ---
  {
    id: 'relic_unknown',
    name: 'The Unknown',
    description: 'Log focus under an completely original subject you custom-made in settings.',
    category: 'relic',
    rarity: 'Epic',
    xpAward: 400,
    secret: true,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'relic_silent',
    name: 'Silent Orb',
    description: 'Mute the audio completely and focus for a full 25-minute cycle.',
    category: 'relic',
    rarity: 'Epic',
    xpAward: 400,
    secret: true,
    progressCurrent: 0,
    progressTarget: 25,
  },
  {
    id: 'relic_ghost',
    name: 'Ghost Session',
    description: 'Focus during the silent hours of the night between 2:00 AM and 4:00 AM.',
    category: 'relic',
    rarity: 'Epic',
    xpAward: 500,
    secret: true,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'relic_midnight',
    name: 'Midnight Echo',
    description: 'Trigger or finish a session exactly spanning the midnight threshold.',
    category: 'relic',
    rarity: 'Epic',
    xpAward: 500,
    secret: true,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'relic_hidden_capsule',
    name: 'Hidden Capsule',
    description: 'Create a backup archive named "secret_capsule" or similar mystical name.',
    category: 'relic',
    rarity: 'Legendary',
    xpAward: 1000,
    secret: true,
    progressCurrent: 0,
    progressTarget: 1,
  },
  {
    id: 'relic_wanderer',
    name: 'The Wanderer',
    description: 'Switch between 5 different focus modes within a single minute.',
    category: 'relic',
    rarity: 'Legendary',
    xpAward: 1000,
    secret: true,
    progressCurrent: 0,
    progressTarget: 5,
  },
  {
    id: 'relic_lost_freq',
    name: 'Lost Frequency',
    description: 'Tune into Pink Noise or a special custom mixture for 30 continuous minutes.',
    category: 'relic',
    rarity: 'Mythic',
    xpAward: 1500,
    secret: true,
    progressCurrent: 0,
    progressTarget: 30,
  },
  {
    id: 'relic_infinity_walker',
    name: 'Infinity Walker',
    description: 'Let the stopwatch/Infinity Pulse cycle run uninterrupted for over 3 hours.',
    category: 'relic',
    rarity: 'Celestial',
    xpAward: 3000,
    secret: true,
    progressCurrent: 0,
    progressTarget: 180,
  },

  // --- LEGENDARY VAULT ---
  {
    id: 'vault_keeper',
    name: 'Orb Keeper',
    description: 'Show masterful alignment by elevating your Timerra focus level to 20.',
    category: 'vault',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 20,
  },
  {
    id: 'vault_legend',
    name: 'Capsule Legend',
    description: 'Generate 10 secure exported backup capsules over time.',
    category: 'vault',
    rarity: 'Legendary',
    xpAward: 1000,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'vault_emperor',
    name: 'Focus Emperor',
    description: 'Command the flow of time by leveling up to 50.',
    category: 'vault',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 50,
  },
  {
    id: 'vault_architect',
    name: 'Master Architect',
    description: 'Catalog and manage 10 distinct custom study subjects.',
    category: 'vault',
    rarity: 'Mythic',
    xpAward: 2500,
    progressCurrent: 0,
    progressTarget: 10,
  },
  {
    id: 'vault_guardian',
    name: 'Timerra Guardian',
    description: 'Establish yourself as a core guardian with 6 consecutive months of focus records.',
    category: 'vault',
    rarity: 'Celestial',
    xpAward: 5000,
    progressCurrent: 0,
    progressTarget: 180, // days roughly
  },
  {
    id: 'vault_last_milestone',
    name: 'The Last Milestone',
    description: 'Reach the ultimate benchmark: Focus Level 100.',
    category: 'vault',
    rarity: 'Celestial',
    xpAward: 10000,
    progressCurrent: 0,
    progressTarget: 100,
  }
];
